import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Myk Klemme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row justify-content-center">
        <div className="col-8">
          <h1>Myk Klemme</h1>
        </div>
      </div>
    </div>
  )
}
